use wasmtime::component::ResourceTable;

use super::WacBackend;

pub struct WacCtx {
    pub wac_backend: WacBackend,
}

impl WacCtx {
    pub fn new(registry_path: String) -> Self {
        let wac_backend: Box<hayride_wac::WacBackend> =
            Box::new(hayride_wac::WacBackend::new(registry_path));
        Self {
            wac_backend: WacBackend(wac_backend),
        }
    }
}

pub trait WacView: Send {
    /// Returns a mutable reference to the wac context.
    fn ctx(&mut self) -> &mut WacCtx;

    /// Returns a mutable reference to the wac resource table.
    fn table(&mut self) -> &mut ResourceTable;
}

impl<T: ?Sized + WacView> WacView for &mut T {
    fn ctx(&mut self) -> &mut WacCtx {
        T::ctx(self)
    }

    fn table(&mut self) -> &mut ResourceTable {
        T::table(self)
    }
}

impl<T: ?Sized + WacView> WacView for Box<T> {
    fn ctx(&mut self) -> &mut WacCtx {
        T::ctx(self)
    }

    fn table(&mut self) -> &mut ResourceTable {
        T::table(self)
    }
}

/// A concrete structure that all generated `Host` traits are implemented for.
///
/// This type serves as a small newtype wrapper to implement all of the `Host`
/// traits for `hayride:wac`. This type is internally used and is only needed if
/// you're interacting with `add_to_linker` functions generated by bindings
/// themselves (or `add_to_linker_get_host`).
///
/// This type is automatically used when using
/// [`add_to_linker_async`](crate::add_to_linker_async)
/// or
/// [`add_to_linker_sync`](crate::add_to_linker_sync)
/// and doesn't need to be manually configured.
#[repr(transparent)]
pub struct WacImpl<T>(pub T);

impl<T: WacView> WacView for WacImpl<T> {
    fn ctx(&mut self) -> &mut WacCtx {
        self.0.ctx()
    }

    fn table(&mut self) -> &mut ResourceTable {
        self.0.table()
    }
}
