use wasmtime::component::ResourceTable;

use super::DBBackend;

pub struct DBCtx {
    pub db_backend: DBBackend,
}

impl DBCtx {
    pub fn new() -> Self {
        let db_backend: Box<hayride_db::DBBackend> =
            Box::new(hayride_db::DBBackend::new());
        Self {
            db_backend: DBBackend(db_backend),
        }
    }
}

pub trait DBView: Send {
    /// Returns a mutable reference to the db context.
    fn ctx(&mut self) -> &mut DBCtx;

    /// Returns a mutable reference to the db resource table.
    fn table(&mut self) -> &mut ResourceTable;
}

impl<T: ?Sized + DBView> DBView for &mut T {
    fn ctx(&mut self) -> &mut DBCtx {
        T::ctx(self)
    }

    fn table(&mut self) -> &mut ResourceTable {
        T::table(self)
    }
}

impl<T: ?Sized + DBView> DBView for Box<T> {
    fn ctx(&mut self) -> &mut DBCtx {
        T::ctx(self)
    }

    fn table(&mut self) -> &mut ResourceTable {
        T::table(self)
    }
}

/// A concrete structure that all generated `Host` traits are implemented for.
///
/// This type serves as a small newtype wrapper to implement all of the `Host`
/// traits for `hayride:wac`. This type is internally used and is only needed if
/// you're interacting with `add_to_linker` functions generated by bindings
/// themselves (or `add_to_linker_get_host`).
///
/// This type is automatically used when using
/// [`add_to_linker_async`](crate::add_to_linker_async)
/// or
/// [`add_to_linker_sync`](crate::add_to_linker_sync)
/// and doesn't need to be manually configured.
#[repr(transparent)]
pub struct DBImpl<T>(pub T);

impl<T: DBView> DBView for DBImpl<T> {
    fn ctx(&mut self) -> &mut DBCtx {
        self.0.ctx()
    }

    fn table(&mut self) -> &mut ResourceTable {
        self.0.table()
    }
}
