[package]
name = "hayride"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = ["crates/hayride-ui"]

[workspace.package]
version = "0.0.1"
authors = ["hayride-dev"]
edition = "2021"

[workspace.dependencies]

[features]
