package hayride:runtime@0.0.1;

world hayride-server {
    include hayride:wasip2/imports@0.0.48;
    include hayride:http/client-server@0.0.48;
}

world hayride-cli {
    include hayride:wasip2/imports@0.0.48;
    include hayride:wasip2/exports@0.0.48;
}

world hayride-ws {
    include hayride:socket/exports@0.0.48;
}

world hayride-ai {
    include hayride:ai/imports@0.0.48;
}

world hayride-core {
    import hayride:core/types@0.0.48;
    import hayride:core/config@0.0.48;
}

world hayride-api {
    import hayride:core/api@0.0.48;
}

world hayride-silo {
    include hayride:silo/imports@0.0.48;
}

world hayride-wac {
    include hayride:wac/imports@0.0.48;
}
