use wasmtime::component::ResourceTable;
pub struct McpCtx {}

impl McpCtx {
    pub fn new() -> Self {
        Self {}
    }
}

pub trait McpView: Send {
    /// Returns a mutable reference to the ml context.
    fn ctx(&mut self) -> &mut McpCtx;

    /// Returns a mutable reference to the ml resource table.
    fn table(&mut self) -> &mut ResourceTable;
}

impl<T: ?Sized + McpView> McpView for &mut T {
    fn ctx(&mut self) -> &mut McpCtx {
        T::ctx(self)
    }

    fn table(&mut self) -> &mut ResourceTable {
        T::table(self)
    }
}

impl<T: ?Sized + McpView> McpView for Box<T> {
    fn ctx(&mut self) -> &mut McpCtx {
        T::ctx(self)
    }

    fn table(&mut self) -> &mut ResourceTable {
        T::table(self)
    }
}

/// A concrete structure that all generated `Host` traits are implemented for.
///
/// This type serves as a small newtype wrapper to implement all of the `Host`
/// traits for `hayride:spawn`. This type is internally used and is only needed if
/// you're interacting with `add_to_linker` functions generated by bindings
/// themselves (or `add_to_linker_get_host`).
///
/// This type is automatically used when using
/// [`add_to_linker_async`](crate::add_to_linker_async)
/// or
/// [`add_to_linker_sync`](crate::add_to_linker_sync)
/// and doesn't need to be manually configured.
#[repr(transparent)]
pub struct McpImpl<T>(pub T);

impl<T: McpView> McpView for McpImpl<T> {
    fn ctx(&mut self) -> &mut McpCtx {
        self.0.ctx()
    }

    fn table(&mut self) -> &mut ResourceTable {
        self.0.table()
    }
}
